export const UPDATE_CURRENT_EXERCISE_TYPE = "UPDATE_CURRENT_EXERCISE_TYPE";
export const GENERATE_NEW_QUESTION = "GENERATE_NEW_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_EXERCISE_LIBRARY = "UPDATE_EXERCISE_LIBRARY";
export const HANDLE_ANSWER = "HANDLE_ANSWER";
export const UPDATE_PROGRESS = "UPDATE_PROGRESS";
export const RESET_PROGRESS = "RESET_PROGRESS";